remote_theme: mmistakes/minimal-mistakes@4.24.0

title: WeatherLink v2 API

url: "https://weatherlink.github.io"
baseurl: /release-notes

search: false

after_footer_scripts:
  - /assets/vendor/weatherlink/js/footer-copyright.js
  - https://cdn.jsdelivr.net/npm/lodash@4.17.11/lodash.min.js

include:
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

plugins:
  - jekyll-include-cache